server:
  port: 8080
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM
    include-exception: false

# Mysql connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        ddl-auto: none
        show-sql: true
        id.new_generator_mappings: false
        storage_engine: innodb
    open-in-view: true

# SPRING SECURITY
#spring.security.user.name=root
#spring.security.user.password=123456
# para retirar login spring security
#spring.security.basic.enable: false

# Jackson
spring.jackson:
  serialization:
    fail-on-empty-beans: false

# SWAGGER2
spring.mvc.pathmatch:
  matching-strategy: ANT_PATH_MATCHER